# Generated by Django 2.2.24 on 2022-02-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0002_business_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeighbourHood',
            new_name='NeighborHood',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
    ]
