# Generated by Django 2.2.24 on 2022-02-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_auto_20220219_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hood',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighborhood',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='NeighborHood',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
